
container = "$PARENT-web-1"
local_path = "$CWD/app"
docker_internal_path = "/usr/src/app"
executable = "pyright-langserver"
pattern = "$HOME/dev/"
log_level = "trace"
patch_pid = ["pyright-langserver"]
